### ISSUE TITLE
Error: No module named nmap

### ISSUE THREAD

**Issue by young9471** [dark-lbp/isf#1]
There are some issues with scanner module：No module named nmap

isf > use scanners/vxworks_6_scan
[-] Error during loading 'icssploit/modules/scanners/vxworks_6_scan'
Error: No module named nmap
It should be valid path to the module. Use <tab> key multiple times for completion.

**Comment by yashrohilla** [comment]
If anyone is still facing this error, you can follow the instructions on: https://github.com/securipy/nmap-scan/issues/26

Example:
- sudo apt-get install python-pip nmap
- sudo pip install python-nmap
